### ISSUE TITLE
Update README formatting

### ISSUE THREAD

**Issue by deeheber** [deeheber/image-ai#4]
Update the presentation of information in the README using a table or something to make the commands/options for each command a bit easier to read.

**Comment by sovetw** [comment]
Hi I would like to work on this issue. Please assign it to me.

**Comment by deeheber** [comment]
Thanks @sovetw

**Comment by sovetw** [comment]
Hi, I updated the readme and created a pull request. I am new to GitHub. Please let me know if you got my pull request and if the edits are satisfactory.

**Comment by deeheber** [comment]
Looks good. Thanks for your help.
